api_platform:
  oauth:
    # To enable or disable OAuth.
    enabled: true

    # The OAuth client ID.
    clientId: '13c2025e4d5bdeadccce0460bb12dfff'

    # The OAuth client secret.
    clientSecret: '7e89d9b76cba0df88be516430204da0e1f71b8e003a3db53efe86a6781f43c4abfe173f06ea5b119b09b714e398890f4c993a4a2fd2dedb3a9ef94c9e4ab7c42'

    # The OAuth type.
    type: 'oauth2'

    # The OAuth flow grant type.
    flow: 'password' # или 'application'

    # The OAuth token url.
    tokenUrl: '/token' # '/oauth/v2/token'

    # The OAuth authentication url.
    authorizationUrl: '/oauth/v2/auth'

    # The OAuth scopes.
    scopes: []